services:
  mysql:
    image: mysql:8.0
    container_name: innovatech-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot"]
      interval: 5s
      timeout: 5s
      retries: 20

  eureka-server:
    build: ./eureka-server
    container_name: innovatech-eureka-server
    ports:
      - "8761:8761"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
