spring.application.name=eureka-server
server.port=8761

# El servidor no se registra a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Tiempo de espera reducido al iniciar
eureka.server.wait-time-in-ms-when-sync-empty=0

# Tiempo antes de considerar instancia caída (en ms, default 90s)
eureka.server.eviction-interval-timer-in-ms=10000
